---
- name: Install requirements for gopass
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - git
    - gnupg
    - rng-tools
    - xsel
    - xclip
    - xorg-xclipboard

- name: Install Gopass
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - gopass

- name: Install gopass-jsonapi for browser integration
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - gopass-jsonapi
  when: gopass__install_jsonapi | bool

- name: Install gopass-hibp for haveibeenpwnd.com integration
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - gopass-hibp
  when: gopass__install_haveibeenpwnd | bool

- name: Install git-credential-gopass as git-credentials helper
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - git-credential-gopass
  when: gopass__install_git_credential | bool
