---
- name: Install requirements for gopass  # noqa: H1901
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: 'present'
    update_cache: true
  loop: "{{ gopass__required_archlinux_packages }}"

- name: Install Gopass  # noqa: H1901
  community.general.pacman:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'gopass'

- name: Install gopass-jsonapi for browser integration  # noqa: H1901
  community.general.pacman:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'gopass-jsonapi'
  when: gopass__install_jsonapi | bool

- name: Install gopass-hibp for haveibeenpwnd.com integration  # noqa: H1901
  community.general.pacman:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'gopass-hibp'
  when: gopass__install_haveibeenpwnd | bool

- name: Install git-credential-gopass as git-credentials helper  # noqa: H1901
  community.general.pacman:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'git-credential-gopass'
  when: gopass__install_git_credential | bool

- name: Install zbar-tools for QR CodeReading using OTP Secrets  # noqa: H1901
  community.general.pacman:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'zbar-tools'
  when: gopass__install_zbar_tools | bool
