---
- name: Install requirements for gopass
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  loop: "{{ gopass__required_packages }}"

- name: Install Gopass
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'gopass'

- name: Install gopass-jsonapi for browser integration
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'gopass-jsonapi'
  when: gopass__install_jsonapi | bool

- name: Install gopass-hibp for haveibeenpwnd.com integration
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'gopass-hibp'
  when: gopass__install_haveibeenpwnd | bool

- name: Install git-credential-gopass as git-credentials helper
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'git-credential-gopass'
  when: gopass__install_git_credential | bool

- name: Install zbar-tools for QR CodeReading using OTP Secrets
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  become: true
  loop:
    - 'zbar-tools'
  when: gopass__install_zbar_tools | bool
