---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Install GoPass Packages
  ansible.builtin.include_tasks:
    file: "{{ lookup('ansible.builtin.first_found', gopass_install) }}"
