---
name: Galaxy release

# yamllint disable-line rule:truthy
on:
  push:
    branches: ['main']
  release:
    types: ['created']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout git repo'
        uses: actions/checkout@v41.0

      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.galaxy_api_key }}
          src_path: .
          api_server: https://galaxy.ansible.com/
